language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: polste

services: docker

install: true

cache:
  directories:
    - $HOME/.m2
    - src/main/WEB-APP/semantic

script:
  - ./mvnw clean verify -Pjacoco && ./mvnw verify -P test-frontend  && ./mvnw coveralls:report

after_script:
  - sudo apt-get update -y
  - sudo apt-get install -y ruby-coveralls
  - cat ./src/main/WEB-APP/coverage/lcov.info | coveralls


