language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

install: true

services: docker

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean test -Pjacoco && ./mvnw verify && ./mvnw coveralls:report

deploy:
  api_key: 459047da-8d27-4703-b367-cdeaa1e091d3
    secure: $HEROKU_API_KEY
    app: teammates-manager-backend
  provider: heroku
