language: node_js
node_js:
  - 12
addons:
  sonarcloud:
    organization: "polste"
cache:
  directories:
    - node_modules
script:
  - npm run test:all
after_script:
  - cat ./coverage/lcov.info | coveralls
  - sonar-scanner
