language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: polste

services: docker

install: true

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean verify -Pjacoco && ./mvnw coveralls:report sonar:sonar
#  - ./mvnw clean verify -Pjacoco && ./mvnw coveralls:report sonar:sonar && ./mvnw clean heroku:deploy


