language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: polste

services: docker

install: true

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean verify -Pjacoco && ./mvnw verify -Pe2e-tests && ./mvnw coveralls:report sonar:sonar

#deploy:
#  api_key: 459047da-8d27-4703-b367-cdeaa1e091d3
#    secure: $HEROKU_API_KEY
#    app: teammates-manager-backend
#  provider: heroku
