language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: polste

services: docker

install: true

cache:
  directories:
    - $HOME/.m2
    - src/main/WEB-APP/semantic

script:
  - ./mvnw clean verify -Pjacoco && ./mvnw verify -Pe2e-backend-tests && ./mvnw verify -P test-frontend  && ./mvnw coveralls:report sonar:sonar


