language: java

dist: xenial

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: polste

services: docker

install: true

cache:
  directories:
    - $HOME/.m2
    - src/main/WEB-APP/semantic

deploy:
  provider: script
  script:  "./mvnw heroku:deploy-only"
  api_key: $HEROKU_API_KEY
  on:
    branch: master
  skip_cleanup: true

script:
  - ./mvnw clean verify -Pjacoco && ./mvnw verify -Pe2e-backend-tests && ./mvnw verify -Ptest-frontend

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./mvnw sonar:sonar


